### ISSUE TITLE
Class 'yii\base\BaseObject' not found

### ISSUE THREAD

**Issue by mydesign** [denostr/yii2-binotel#1]
in denostr/yii2-binotel/src/Client.php:9

**Comment by denostr** [comment]
What is your yii2 version? 
In v2.0.13 yii\base\Object class deprecated.
See yii2 [CHANGELOG](https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md)

**Comment by mydesign** [comment]
Yes, upgrade and it work!
